name: test

on:
  push:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/tests.yml
  pull_request:
    branches: [main]
    paths:
      - src/**
      - .github/workflows/tests.yml

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: 11
    
    - name: Setup and execute Gradle 'test' task
      uses: gradle/gradle-build-action@v2
      with:
        arguments: test
